### ISSUE TITLE
Robovac G30 keeps getting error status after update 1.2.0

### ISSUE THREAD

**Issue by silviudc** [CodeFoodPixels/robovac#57]
I updated to latest version and now one of my vacuums (the G30 robovac) keeps going between docked and error status.
![image](https://github.com/CodeFoodPixels/robovac/assets/17740184/acaa01f3-50a1-4bf7-a926-4f0f1d3c7f32)

Where there is no error.
I see loads of messages with debug enabled, not sure if normal.
```
2024-02-26 21:12:33.337 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to bfd6df67aa715fe6a83ksw (192.168.0.33:6668): Message(0x9, b'', 0, <Device bfd6df67aa715fe6a83ksw (192.168.0.33:6668)>)
2024-02-26 21:12:33.337 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connecting to bfd6df67aa715fe6a83ksw (192.168.0.33:6668)
2024-02-26 21:12:33.344 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Received message from bfd6df67aa715fe6a83ksw (192.168.0.33:6668): Message(0x9, b'', 0, None)
2024-02-26 21:12:33.379 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Disconnected from bfd6df67aa715fe6a83ksw (192.168.0.33:6668)
2024-02-26 21:12:33.448 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Processing queue. Current length: 3272
2024-02-26 21:12:33.448 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to bfd6df67aa715fe6a83ksw (192.168.0.33:6668): Message(0x9, b'', 0, <Device bfd6df67aa715fe6a83ksw (192.168.0.33:6668)>)
2024-02-26 21:12:33.450 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connecting to bfd6df67aa715fe6a83ksw (192.168.0.33:6668)
2024-02-26 21:12:33.455 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Received message from bfd6df67aa715fe6a83ksw (192.168.0.33:6668): Message(0x9, b'', 0, None)
2024-02-26 21:12:33.498 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Disconnected from bfd6df67aa715fe6a83ksw (192.168.0.33:6668)
2024-02-26 21:12:33.557 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Processing queue. Current length: 3397
2024-02-26 21:12:33.558 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to bfd6df67aa715fe6a83ksw (192.168.0.33:6668): Message(0x9, b'', 0, <Device bfd6df67aa715fe6a83ksw (192.168.0.33:6668)>)
2024-02-26 21:12:33.558 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connecting to bfd6df67aa715fe6a83ksw (192.168.0.33:6668)
2024-02-26 21:12:33.609 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Disconnected from bfd6df67aa715fe6a83ksw (192.168.0.33:6668)
2024-02-26 21:12:33.714 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Processing queue. Current length: 3403
2024-02-26 21:12:33.714 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to bfd6df67aa715fe6a83ksw (192.168.0.33:6668): Message(0x9, b'', 0, <Device bfd6df67aa715fe6a83ksw (192.168.0.33:6668)>)
2024-02-26 21:12:33.715 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connecting to bfd6df67aa715fe6a83ksw (192.168.0.33:6668)
2024-02-26 21:12:33.756 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Received message from bfd6df67aa715fe6a83ksw (192.168.0.33:6668): Message(0x9, b'', 0, None)
```

**Comment by silviudc** [comment]
Yeah I was on 1.2.1, attempted a few reboots of Ha and the vacuum and no joy.
Went down to 1.1.1 just now and the wrong error status went away so it started happening in 1.2.1 or also in 1.2.0

**Comment by KyleStilkey** [comment]
Same issue I'm seeing here I'll get my logs when I'm home but same issue with it going to an error state them docked about every couple of minutes.

**Comment by ea5522** [comment]
Same issue here and same log messages. Also its freezing home assistant

**Comment by CodeFoodPixels** [comment]
1.2.0 has quite a serious bug in it that can cause your HA instance to grind to a halt. In 1.2.2 I've adjusted the timeouts, which should give it a little more time to succeed.

> Same issue here and same log messages. Also its freezing home assistant
@ea5522 Are you on version 1.2.1 or 1.2.0? 1.2.1 and 1.2.2 shouldn't have the freezing issue

**Comment by ea5522** [comment]
> 1.2.0 has quite a serious bug in it that can cause your HA instance to grind to a halt. In 1.2.2 I've adjusted the timeouts, which should give it a little more time to succeed.
> 
> > Same issue here and same log messages. Also its freezing home assistant
> > @ea5522 Are you on version 1.2.1 or 1.2.0? 1.2.1 and 1.2.2 shouldn't have the freezing issue

i'm on 1.2.1. Doing an update to 1.2.2 and will report back.

**Comment by ea5522** [comment]
Home assistant is working fine, but all the vacuums are unavailable.

**Comment by silviudc** [comment]
Seems to be working with 1.2.2 it did took a while to pick them up after restart of HA but hopefully all good from now on, thanks for the quick fixes

**Comment by silviudc** [comment]
Spoke too soon, the G30 still going to error every now and again :(
![image](https://github.com/CodeFoodPixels/robovac/assets/17740184/79d1fb1f-775e-4071-bd5a-582feb92c11c)

**Comment by ea5522** [comment]
I just noticed that some info is missing. Like it won't show fan speed status or the actual error.

**Comment by CodeFoodPixels** [comment]
> Spoke too soon, the G30 still going to error every now and again :(
If homeassistant fails to get an update from the vacuum in 3 consecutive attempts (each attempt is 1 minute apart), then it will be marked in an error state.

**Comment by silviudc** [comment]
Seeing many of these in the logs:
```
	Line 2898: 2024-02-28 07:38:37.169 WARNING (MainThread) [custom_components.robovac.vacuum] Update errored. Current update failure count: 2. Reason: Timed out waiting for response to sequence number 134542994
	Line 2899: 2024-02-28 07:38:37.170 WARNING (MainThread) [custom_components.robovac.vacuum] Update errored. Current update failure count: 3. Reason: Timed out waiting for response to sequence number 134542994
	Line 2902: 2024-02-28 07:41:37.953 WARNING (MainThread) [custom_components.robovac.vacuum] Update errored. Current update failure count: 1. Reason: Timed out waiting for response to sequence number 134723626
	Line 2903: 2024-02-28 07:41:37.954 WARNING (MainThread) [custom_components.robovac.vacuum] Update errored. Current update failure count: 1. Reason: Timed out waiting for response to sequence number 134723626
	Line 3017: 2024-02-28 07:42:39.166 WARNING (MainThread) [custom_components.robovac.vacuum] Update errored. Current update failure count: 2. Reason: Timed out waiting for response to sequence number 134785232
	Line 3023: 2024-02-28 07:43:41.402 WARNING (MainThread) [custom_components.robovac.vacuum] Update errored. Current update failure count: 1. Reason: Timed out waiting for response to sequence number 134845393
	Line 3024: 2024-02-28 07:43:41.402 WARNING (MainThread) [custom_components.robovac.vacuum] Update errored. Current update failure count: 3. Reason: Timed out waiting for response to sequence number 134845393
	Line 3026: 2024-02-28 07:44:41.979 WARNING (MainThread) [custom_components.robovac.vacuum] Update errored. Current update failure count: 2. Reason: Timed out waiting for response to sequence number 134906798
	Line 3027: 2024-02-28 07:44:41.980 WARNING (MainThread) [custom_components.robovac.vacuum] Update errored. Current update failure count: 4. Reason: Timed out waiting for response to sequence number 134906798
	Line 3436: 2024-02-28 07:49:49.683 WARNING (MainThread) [custom_components.robovac.vacuum] Update errored. Current update failure count: 1. Reason: Timed out waiting for response to sequence number 135211222
```
Affecting both vacuums now.

**Comment by silviudc** [comment]
Just a load of these:
```
2024-02-28 17:54:28.538 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to 0753038684f3ebf4b8d5 (192.168.0.94:6668): Message(0x9, b'', 0, <Device 0753038684f3ebf4b8d5 (192.168.0.94:6668)>)
2024-02-28 17:54:28.607 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Processing queue. Current length: 40443
2024-02-28 17:54:28.607 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to bfd6df67aa715fe6a83ksw (192.168.0.33:6668): Message(0x9, b'', 0, <Device bfd6df67aa715fe6a83ksw (192.168.0.33:6668)>)
2024-02-28 17:54:28.641 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Processing queue. Current length: 2655
2024-02-28 17:54:28.641 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to 0753038684f3ebf4b8d5 (192.168.0.94:6668): Message(0x9, b'', 0, <Device 0753038684f3ebf4b8d5 (192.168.0.94:6668)>)
2024-02-28 17:54:28.665 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Received message from bfd6df67aa715fe6a83ksw (192.168.0.33:6668): Message(0x9, b'', 0, None)
2024-02-28 17:54:28.670 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Received message from 0753038684f3ebf4b8d5 (192.168.0.94:6668): Message(0x9, b'', 0, None)
2024-02-28 17:54:28.678 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Received message from 0753038684f3ebf4b8d5 (192.168.0.94:6668): Message(0x9, b'', 0, None)
2024-02-28 17:54:28.727 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Processing queue. Current length: 40442
2024-02-28 17:54:28.727 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to bfd6df67aa715fe6a83ksw (192.168.0.33:6668): Message(0x9, b'', 0, <Device bfd6df67aa715fe6a83ksw (192.168.0.33:6668)>)
2024-02-28 17:54:28.744 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Processing queue. Current length: 2654
2024-02-28 17:54:28.745 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to 0753038684f3ebf4b8d5 (192.168.0.94:6668): Message(0x9, b'', 0, <Device 0753038684f3ebf4b8d5 (192.168.0.94:6668)>)
2024-02-28 17:54:28.745 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Received message from bfd6df67aa715fe6a83ksw (192.168.0.33:6668): Message(0x9, b'', 0, None)
2024-02-28 17:54:28.846 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Processing queue. Current length: 40441
2024-02-28 17:54:28.847 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to bfd6df67aa715fe6a83ksw (192.168.0.33:6668): Message(0x9, b'', 0, <Device bfd6df67aa715fe6a83ksw (192.168.0.33:6668)>)
2024-02-28 17:54:28.853 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Processing queue. Current length: 2653
2024-02-28 17:54:28.853 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to 0753038684f3ebf4b8d5 (192.168.0.94:6668): Message(0x9, b'', 0, <Device 0753038684f3ebf4b8d5 (192.168.0.94:6668)>)
2024-02-28 17:54:28.887 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Received message from 0753038684f3ebf4b8d5 (192.168.0.94:6668): Message(0x9, b'', 0, None)
2024-02-28 17:54:28.887 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Received message from bfd6df67aa715fe6a83ksw (192.168.0.33:6668): Message(0x9, b'', 0, None)
2024-02-28 17:54:28.890 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Received message from 0753038684f3ebf4b8d5 (192.168.0.94:6668): Message(0x9, b'', 0, None)
2024-02-28 17:54:28.966 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Processing queue. Current length: 40440
2024-02-28 17:54:28.966 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to bfd6df67aa715fe6a83ksw (192.168.0.33:6668): Message(0x9, b'', 0, <Device bfd6df67aa715fe6a83ksw (192.168.0.33:6668)>)
2024-02-28 17:54:28.977 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Processing queue. Current length: 2665
2024-02-28 17:54:28.977 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to 0753038684f3ebf4b8d5 (192.168.0.94:6668): Message(0x9, b'', 0, <Device 0753038684f3ebf4b8d5 (192.168.0.94:6668)>)
2024-02-28 17:54:28.988 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Received message from bfd6df67aa715fe6a83ksw (192.168.0.33:6668): Message(0x9, b'', 0, None)
2024-02-28 17:54:28.989 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Received message from 0753038684f3ebf4b8d5 (192.168.0.94:6668): Message(0x9, b'', 0, None)
2024-02-28 17:54:28.998 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Disconnected from bfd6df67aa715fe6a83ksw (192.168.0.33:6668)
2024-02-28 17:54:29.001 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Disconnected from 0753038684f3ebf4b8d5 (192.168.0.94:6668)
2024-02-28 17:54:29.112 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Processing queue. Current length: 28459
2024-02-28 17:54:29.112 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to bfd6df67aa715fe6a83ksw (192.168.0.33:6668): Message(0x9, b'', 0, <Device bfd6df67aa715fe6a83ksw (192.168.0.33:6668)>)
2024-02-28 17:54:29.112 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connecting to bfd6df67aa715fe6a83ksw (192.168.0.33:6668)
2024-02-28 17:54:29.504 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Processing queue. Current length: 1907
2024-02-28 17:54:29.504 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to 0753038684f3ebf4b8d5 (192.168.0.94:6668): Message(0x9, b'', 0, <Device 0753038684f3ebf4b8d5 (192.168.0.94:6668)>)
2024-02-28 17:54:29.504 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connecting to 0753038684f3ebf4b8d5 (192.168.0.94:6668)
2024-02-28 17:54:29.560 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Disconnected from bfd6df67aa715fe6a83ksw (192.168.0.33:6668)
2024-02-28 17:54:31.444 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Processing queue. Current length: 27263
2024-02-28 17:54:31.444 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to bfd6df67aa715fe6a83ksw (192.168.0.33:6668): Message(0x9, b'', 0, <Device bfd6df67aa715fe6a83ksw (192.168.0.33:6668)>)
2024-02-28 17:54:31.446 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connecting to bfd6df67aa715fe6a83ksw (192.168.0.33:6668)
2024-02-28 17:54:31.456 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Disconnected from 0753038684f3ebf4b8d5 (192.168.0.94:6668)
```
Whatever v1.1.9 was doing, keep doing that :)

**Comment by CodeFoodPixels** [comment]
Turns out I'm really stupid when I'm tired 😅: https://github.com/CodeFoodPixels/robovac/commit/ac0dbdd11a0d4b325619682bf26e2f8e6ac9da64

The fact that it's returning lines like this: `Processing queue. Current length: 27263` means something was up, I had some guards around it not starting another ping task when it reconnects, but I'd missed a couple of underscores and it meant every time it disconnected, it was adding more and more ping task loops.

New release should fix it.

**Comment by silviudc** [comment]
All good from my side since 1.2.3, still see about two or three "error" in about 10 hours which might be genuine signal issues.

**Comment by KyleStilkey** [comment]
Updated to 1.2.3 so far good ill continue to monitor overtime.

**Comment by FuturamaPhill** [comment]
> @FuturamaPhill I'm pulling your conversation into here as it seems linked to this issue. Please could you enable debug logging and post a sample of your logs since upgrading to 1.2.3 please

Attached the logs as a file but here are the hightlights as a lot of connection reset entries: 

[home-assistant_2024-03-01T11-14-33.362Z.log](https://github.com/CodeFoodPixels/robovac/files/14460386/home-assistant_2024-03-01T11-14-33.362Z.log)

```
2024-03-01 11:13:52.972 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Processing queue. Current length: 1
2024-03-01 11:13:52.972 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668): Message(0xa, {'gwId': 'bf4b0ace39a5f9f09ajma7', 'devId': 'bf4b0ace39a5f9f09ajma7'}, 12163002, <Device bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)>)
2024-03-01 11:13:52.972 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connecting to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)

2024-03-01 11:13:53.077 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connection reset
2024-03-01 11:13:53.078 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Processing queue. Current length: 1
2024-03-01 11:13:53.078 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668): Message(0x9, b'', 0, <Device bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)>)
2024-03-01 11:13:53.078 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Retrying send due to error. Connection to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668) failed: [Errno 104] Connection reset by peer
2024-03-01 11:13:53.078 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connection reset

2024-03-01 11:13:53.328 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connection reset
2024-03-01 11:13:53.332 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668): Message(0x9, b'', 0, <Device bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)>)
2024-03-01 11:13:53.332 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Retrying send due to error. Connection to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668) failed: [Errno 104] Connection reset by peer
2024-03-01 11:13:53.332 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connection reset

2024-03-01 11:13:53.622 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connection reset
2024-03-01 11:13:53.629 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668): Message(0x9, b'', 0, <Device bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)>)
2024-03-01 11:13:53.629 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Disconnected from bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)
2024-03-01 11:13:53.629 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] 1 failures. Most recent: Connection to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668) failed: [Errno 104] Connection reset by peer
2024-03-01 11:13:53.629 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connection reset
2024-03-01 11:14:03.001 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Processing queue. Current length: 1
2024-03-01 11:14:03.001 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668): Message(0x9, b'', 0, <Device bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)>)
2024-03-01 11:14:03.001 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connecting to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)
2024-03-01 11:14:03.020 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connection reset
```

**Comment by CodeFoodPixels** [comment]
@FuturamaPhill It looks like its struggling to connect or maintain a connection with your vacuum. Is there anything special about how your network is set up or configured?

**Comment by FuturamaPhill** [comment]
@CodeFoodPixels no nothing special, modem into Ubiquiti AP no vlans or anything like that

**Comment by CodeFoodPixels** [comment]
@FuturamaPhill could you try 1.2.4 please?

**Comment by FuturamaPhill** [comment]
@CodeFoodPixels still having issues on 1.2.4

[home-assistant_2024-03-01T15-34-55.387Z.log](https://github.com/CodeFoodPixels/robovac/files/14462978/home-assistant_2024-03-01T15-34-55.387Z.log)


```
2024-03-01 15:34:22.165 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connection reset
2024-03-01 15:34:22.167 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668): Message(0x9, b'', 0, <Device bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)>)
2024-03-01 15:34:22.167 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Retrying send due to error. Connection to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668) failed: [Errno 104] Connection reset by peer
2024-03-01 15:34:22.167 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connection reset
```

```
2024-03-01 15:34:22.417 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connection reset
2024-03-01 15:34:22.417 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668): Message(0x9, b'', 0, <Device bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)>)
2024-03-01 15:34:22.417 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Disconnected from bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)
2024-03-01 15:34:22.417 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] 1 failures. Most recent: Connection to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668) failed: [Errno 104] Connection reset by peer
2024-03-01 15:34:22.417 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connection reset
2024-03-01 15:34:31.765 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Processing queue. Current length: 1
2024-03-01 15:34:31.765 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Sending to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668): Message(0x9, b'', 0, <Device bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)>)
2024-03-01 15:34:31.766 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connecting to bf4b0ace39a5f9f09ajma7 (192.168.0.144:6668)
2024-03-01 15:34:31.783 DEBUG (MainThread) [custom_components.robovac.tuyalocalapi] Connection reset
```
